// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuwaYUqQ2b_yJ2s6aes0js575_3Y4K728',
    appId: '1:368715832190:web:5acfff87534d4abf9c712f',
    messagingSenderId: '368715832190',
    projectId: 'brillanza-47f0d',
    authDomain: 'brillanza-47f0d.firebaseapp.com',
    storageBucket: 'brillanza-47f0d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Q_seJY86dOLtuJJuw7ElTPLyWUN7mHk',
    appId: '1:368715832190:android:c495d631f07237f69c712f',
    messagingSenderId: '368715832190',
    projectId: 'brillanza-47f0d',
    storageBucket: 'brillanza-47f0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFDjCBGHSsNLfzjwx5HMvkURGnzZ98l5s',
    appId: '1:368715832190:ios:10d1b58a11a753e89c712f',
    messagingSenderId: '368715832190',
    projectId: 'brillanza-47f0d',
    storageBucket: 'brillanza-47f0d.firebasestorage.app',
    iosBundleId: 'com.example.brillanzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFDjCBGHSsNLfzjwx5HMvkURGnzZ98l5s',
    appId: '1:368715832190:ios:10d1b58a11a753e89c712f',
    messagingSenderId: '368715832190',
    projectId: 'brillanza-47f0d',
    storageBucket: 'brillanza-47f0d.firebasestorage.app',
    iosBundleId: 'com.example.brillanzaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuwaYUqQ2b_yJ2s6aes0js575_3Y4K728',
    appId: '1:368715832190:web:bfa2e57173612e439c712f',
    messagingSenderId: '368715832190',
    projectId: 'brillanza-47f0d',
    authDomain: 'brillanza-47f0d.firebaseapp.com',
    storageBucket: 'brillanza-47f0d.firebasestorage.app',
  );
}
